// <auto-generated />
using System;
using Finanzas.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Finanzas.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260818185712_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Finanzas.Api.Models.EspacioFinanciero", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CreadoPorId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreadoPorId");

                    b.ToTable("EspaciosFinancieros");
                });

            modelBuilder.Entity("Finanzas.Api.Models.EspacioUsuario", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("EspacioFinancieroId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("FechaUnion")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Rol")
                        .HasColumnType("int");

                    b.Property<long>("UsuarioId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("EspacioFinancieroId", "UsuarioId")
                        .IsUnique();

                    b.ToTable("EspaciosUsuarios");
                });

            modelBuilder.Entity("Finanzas.Api.Models.Usuario", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Finanzas.Api.Models.EspacioFinanciero", b =>
                {
                    b.HasOne("Finanzas.Api.Models.Usuario", "CreadoPor")
                        .WithMany()
                        .HasForeignKey("CreadoPorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreadoPor");
                });

            modelBuilder.Entity("Finanzas.Api.Models.EspacioUsuario", b =>
                {
                    b.HasOne("Finanzas.Api.Models.EspacioFinanciero", "EspacioFinanciero")
                        .WithMany("Usuarios")
                        .HasForeignKey("EspacioFinancieroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Finanzas.Api.Models.Usuario", "Usuario")
                        .WithMany("Espacios")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EspacioFinanciero");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Finanzas.Api.Models.EspacioFinanciero", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("Finanzas.Api.Models.Usuario", b =>
                {
                    b.Navigation("Espacios");
                });
#pragma warning restore 612, 618
        }
    }
}
