// <auto-generated />
using System;
using Finanzas.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Finanzas.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Finanzas.Api.Models.Categoria", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)");

                    b.Property<long>("EspacioFinancieroId")
                        .HasColumnType("bigint");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EspacioFinancieroId", "Nombre", "Tipo")
                        .IsUnique();

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("Finanzas.Api.Models.Cuenta", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)");

                    b.Property<long?>("EntidadFinancieraId")
                        .HasColumnType("bigint");

                    b.Property<long>("EspacioFinancieroId")
                        .HasColumnType("bigint");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<long?>("PropietarioId")
                        .HasColumnType("bigint");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EntidadFinancieraId");

                    b.HasIndex("EspacioFinancieroId");

                    b.HasIndex("PropietarioId");

                    b.ToTable("Cuentas");
                });

            modelBuilder.Entity("Finanzas.Api.Models.Devolucion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("DebeUsuarioId")
                        .HasColumnType("bigint");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateOnly?>("FechaPago")
                        .HasColumnType("date");

                    b.Property<long>("GastoId")
                        .HasColumnType("bigint");

                    b.Property<string>("Observacion")
                        .HasColumnType("longtext");

                    b.Property<long?>("RecibeCuentaId")
                        .HasColumnType("bigint");

                    b.Property<long?>("RecibeUsuarioId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Valor")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("ValorPagado")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.HasKey("Id");

                    b.HasIndex("DebeUsuarioId");

                    b.HasIndex("GastoId");

                    b.HasIndex("RecibeCuentaId");

                    b.HasIndex("RecibeUsuarioId");

                    b.ToTable("Devoluciones");
                });

            modelBuilder.Entity("Finanzas.Api.Models.EntidadFinanciera", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("EntidadesFinancieras");
                });

            modelBuilder.Entity("Finanzas.Api.Models.EspacioFinanciero", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CreadoPorId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreadoPorId");

                    b.ToTable("EspaciosFinancieros");
                });

            modelBuilder.Entity("Finanzas.Api.Models.EspacioUsuario", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("EspacioFinancieroId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("FechaUnion")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Rol")
                        .HasColumnType("int");

                    b.Property<long>("UsuarioId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("EspacioFinancieroId", "UsuarioId")
                        .IsUnique();

                    b.ToTable("EspaciosUsuarios");
                });

            modelBuilder.Entity("Finanzas.Api.Models.Gasto", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("CategoriaId")
                        .HasColumnType("bigint");

                    b.Property<string>("Concepto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<long?>("CuentaId")
                        .HasColumnType("bigint");

                    b.Property<long>("EspacioFinancieroId")
                        .HasColumnType("bigint");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("GastoFijoId")
                        .HasColumnType("bigint");

                    b.Property<string>("Observacion")
                        .HasColumnType("longtext");

                    b.Property<long?>("PagadoPorId")
                        .HasColumnType("bigint");

                    b.Property<long>("RegistradoPorId")
                        .HasColumnType("bigint");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.Property<decimal>("Valor")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("CuentaId");

                    b.HasIndex("EspacioFinancieroId");

                    b.HasIndex("GastoFijoId");

                    b.HasIndex("PagadoPorId");

                    b.HasIndex("RegistradoPorId");

                    b.ToTable("Gastos");
                });

            modelBuilder.Entity("Finanzas.Api.Models.GastoFijo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)");

                    b.Property<long?>("CategoriaId")
                        .HasColumnType("bigint");

                    b.Property<string>("Concepto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<byte?>("DiaVencimiento")
                        .HasColumnType("tinyint unsigned");

                    b.Property<long>("EspacioFinancieroId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal?>("ValorEstimado")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("EspacioFinancieroId");

                    b.ToTable("GastosFijos");
                });

            modelBuilder.Entity("Finanzas.Api.Models.Ingreso", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("CategoriaId")
                        .HasColumnType("bigint");

                    b.Property<string>("Concepto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<long?>("CuentaId")
                        .HasColumnType("bigint");

                    b.Property<long>("EspacioFinancieroId")
                        .HasColumnType("bigint");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Observacion")
                        .HasColumnType("longtext");

                    b.Property<decimal>("PorcentajeAporte")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<long>("UsuarioId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Valor")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("CuentaId");

                    b.HasIndex("EspacioFinancieroId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Ingresos");
                });

            modelBuilder.Entity("Finanzas.Api.Models.Usuario", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Finanzas.Api.Models.Categoria", b =>
                {
                    b.HasOne("Finanzas.Api.Models.EspacioFinanciero", "EspacioFinanciero")
                        .WithMany()
                        .HasForeignKey("EspacioFinancieroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EspacioFinanciero");
                });

            modelBuilder.Entity("Finanzas.Api.Models.Cuenta", b =>
                {
                    b.HasOne("Finanzas.Api.Models.EntidadFinanciera", "EntidadFinanciera")
                        .WithMany()
                        .HasForeignKey("EntidadFinancieraId");

                    b.HasOne("Finanzas.Api.Models.EspacioFinanciero", "EspacioFinanciero")
                        .WithMany()
                        .HasForeignKey("EspacioFinancieroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Finanzas.Api.Models.Usuario", "Propietario")
                        .WithMany()
                        .HasForeignKey("PropietarioId");

                    b.Navigation("EntidadFinanciera");

                    b.Navigation("EspacioFinanciero");

                    b.Navigation("Propietario");
                });

            modelBuilder.Entity("Finanzas.Api.Models.Devolucion", b =>
                {
                    b.HasOne("Finanzas.Api.Models.Usuario", "DebeUsuario")
                        .WithMany()
                        .HasForeignKey("DebeUsuarioId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Finanzas.Api.Models.Gasto", "Gasto")
                        .WithMany("Devoluciones")
                        .HasForeignKey("GastoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Finanzas.Api.Models.Cuenta", "RecibeCuenta")
                        .WithMany()
                        .HasForeignKey("RecibeCuentaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Finanzas.Api.Models.Usuario", "RecibeUsuario")
                        .WithMany()
                        .HasForeignKey("RecibeUsuarioId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("DebeUsuario");

                    b.Navigation("Gasto");

                    b.Navigation("RecibeCuenta");

                    b.Navigation("RecibeUsuario");
                });

            modelBuilder.Entity("Finanzas.Api.Models.EspacioFinanciero", b =>
                {
                    b.HasOne("Finanzas.Api.Models.Usuario", "CreadoPor")
                        .WithMany()
                        .HasForeignKey("CreadoPorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreadoPor");
                });

            modelBuilder.Entity("Finanzas.Api.Models.EspacioUsuario", b =>
                {
                    b.HasOne("Finanzas.Api.Models.EspacioFinanciero", "EspacioFinanciero")
                        .WithMany("Usuarios")
                        .HasForeignKey("EspacioFinancieroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Finanzas.Api.Models.Usuario", "Usuario")
                        .WithMany("Espacios")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EspacioFinanciero");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Finanzas.Api.Models.Gasto", b =>
                {
                    b.HasOne("Finanzas.Api.Models.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaId");

                    b.HasOne("Finanzas.Api.Models.Cuenta", "Cuenta")
                        .WithMany()
                        .HasForeignKey("CuentaId");

                    b.HasOne("Finanzas.Api.Models.EspacioFinanciero", "EspacioFinanciero")
                        .WithMany()
                        .HasForeignKey("EspacioFinancieroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Finanzas.Api.Models.GastoFijo", "GastoFijo")
                        .WithMany()
                        .HasForeignKey("GastoFijoId");

                    b.HasOne("Finanzas.Api.Models.Usuario", "PagadoPor")
                        .WithMany()
                        .HasForeignKey("PagadoPorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Finanzas.Api.Models.Usuario", "RegistradoPor")
                        .WithMany()
                        .HasForeignKey("RegistradoPorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Cuenta");

                    b.Navigation("EspacioFinanciero");

                    b.Navigation("GastoFijo");

                    b.Navigation("PagadoPor");

                    b.Navigation("RegistradoPor");
                });

            modelBuilder.Entity("Finanzas.Api.Models.GastoFijo", b =>
                {
                    b.HasOne("Finanzas.Api.Models.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaId");

                    b.HasOne("Finanzas.Api.Models.EspacioFinanciero", "EspacioFinanciero")
                        .WithMany()
                        .HasForeignKey("EspacioFinancieroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("EspacioFinanciero");
                });

            modelBuilder.Entity("Finanzas.Api.Models.Ingreso", b =>
                {
                    b.HasOne("Finanzas.Api.Models.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaId");

                    b.HasOne("Finanzas.Api.Models.Cuenta", "Cuenta")
                        .WithMany()
                        .HasForeignKey("CuentaId");

                    b.HasOne("Finanzas.Api.Models.EspacioFinanciero", "EspacioFinanciero")
                        .WithMany()
                        .HasForeignKey("EspacioFinancieroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Finanzas.Api.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Cuenta");

                    b.Navigation("EspacioFinanciero");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Finanzas.Api.Models.EspacioFinanciero", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("Finanzas.Api.Models.Gasto", b =>
                {
                    b.Navigation("Devoluciones");
                });

            modelBuilder.Entity("Finanzas.Api.Models.Usuario", b =>
                {
                    b.Navigation("Espacios");
                });
#pragma warning restore 612, 618
        }
    }
}
